### ISSUE TITLE
cant set value

### ISSUE THREAD

**Issue by kaytitulaer2008** [nmaggioni/Simple-JSONdb#13] opened 2021-12-12 18:01 UTC
if i want to add something to the database, it wont work. no error. it just dosnt write it to the file
code:
`db.set(key, JSON.stringify(owner));`
`db.sync();`

**Comment by nmaggioni** [comment] 2021-12-12 18:24
I'm betting on a duplicate of #10. If that doesn't apply, please attach a more complete snippet of what you're trying to achieve.

**Comment by Artiesy** [comment] 2022-01-16 18:36
you dont need to JSON.stringify

**Closed** 2022-01-17 11:20 UTC
Labels: invalid
