### ISSUE TITLE
Error: UNKNOWN: unknown error, open

### ISSUE THREAD

**Issue by lordbah** [nmaggioni/Simple-JSONdb#2] opened 2017-09-06 20:40 UTC
I do several set() in a row, and after a seemingly random but small number of calls (1-7) it bombs.

```
Error: Error while writing to path "./database.json": Error: UNKNOWN: unknown error, open '<path omitted>\database.json'
    at JSONdb.sync (...\node_modules\simple-json-db\jsondb.js:154:15)
    at JSONdb.set (...\node_modules\simple-json-db\jsondb.js:95:54)
```

The line of code in jsondb.js:
`throw new Error(`Error while writing to path "${this.filePath}": ${err}`);
`
err contains errno=-4094, which I haven't been able to find anywhere.

Maybe colliding with virus scanner?

So I'm catching the error in a retry loop. I've seen it take as many as 5 retries before it succeeds.

There is only one running instance of the program. It is using the default, writeFileSync.

simple-json-db 1.2.1, node 8.2.1.

**Comment by nmaggioni** [comment] 2017-09-06 20:50
On which platform/hardware/OS is Node running on? Do you have a relevant snippet of code to share?

**Comment by lordbah** [comment] 2017-09-06 21:46
Windows 7 64-bit, Intel Xeon. I'll try to put some code together tomorrow.

**Comment by lordbah** [comment] 2017-09-07 15:56
Can you read https://github.com/lordbah/simple-json-db-2 ?

**Comment by nmaggioni** [comment] 2017-09-07 20:22
I cannot reproduce any error neither on my Linux box, nor on a Windows 7 VM - `set`s succeed at the first try as usual and the _json_ file correctly reflects the changes.

Here's a small patch I used to verify every step: [logging_patch.txt](https://github.com/nmaggioni/Simple-JSONdb/files/1286022/logging_patch.txt) - I also randomly reordered the `set` calls in the main file to check that there were no ghost calls.

Is your _json_ db placed on a network/shared folder? I guess there is something limiting your write rate on it. Do you have any other hw/OS to test the snippet with?

**Comment by lordbah** [comment] 2017-09-07 21:37
File is on local disk (SSD actually). 

Just found something potentially interesting: running in Git Bash shell window (seems to be called mintty.exe) as I have been, I see many retries required; ditto when I run inside Visual Code launched from that window. But when run in a Windows cmd window it sometimes runs through without error and sometimes requires just 1 retry on 1 set (same error code).

On Linux (Ubuntu 17.04) on my laptop I have never seen it require a retry.

**Comment by lordbah** [comment] 2017-09-07 21:46
I figured out how to exclude this folder from the virus scanner, and I no longer see the error and retries. It is "System Center Endpoint Protection", some IT-pushed thing.

**Comment by nmaggioni** [comment] 2017-09-07 21:48
Sounds great! It could have been some kind of heuristic trying to prevent worm replication, maybe. Weird, but plausible.

I'll close this issue, feel free to reopen it in case this comes up again.

**Closed by nmaggioni** 2017-09-07 21:48 UTC
